# 十六进制配置
## 文档：https://hexo.io/docs/configuration.html
## 来源：https://github.com/hexojs/hexo/

# 主题设置
theme: stellar
avatar: https://cdn.jsdelivr.net/gh/Less-star/image-host/Wallpaper/favicon.png

# 网站信息∂
title: 少星部落阁
subtitle: 勿忘初心
description: 七窍通了六窍——一窍不通
author: 少 星
email: 262782714@qq.com
language: zh-CN

metadata:
  author_id: 少星
  language: zh-CN

# 网站logo
inject:
  head:
    - <link rel="apple-touch-icon" sizes="180x180" href="https://cdn.jsdelivr.net/gh/Less-star/image-host/Wallpaper/favicon.png">
    - <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/Less-star/image-host/Wallpaper/favicon.png">

permalink: :abbrlink.html  # 此处可以自己设置，也可以直接使用 :/abbrlink
abbrlink:
    alg: crc32   #算法： crc16(default) and crc32
    rep: hex     #进制： dec(default) and hex

# 分页设置
# Pagination
## 设置为 0 禁用分页
per_page: 5
pagination_dir: page

# 网站URL
url: https://shaoxing.vercel.app # https://shaoxing.netlify.app # 
# 如果您的站点位于子目录中，请修改root：/子目录路径
root: /

# 自定义生成目录
# public_dir: docs

pretty_urls:
  trailing_index: false # 设置为false可从固定链接中删除尾随index.html

# 一键部署github
# 部署
deploy:
  type: git
  repo: https://github.com/Less-star/less-star.github.io.git
  # example, https://less-star.github.io/
  branch: gh-pages
# RSS订阅-需要安装 hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 100

# Admin
admin:
    name: shaoxing
    password: ainiyibeizi
    secret: hey ainiyibeizi
    expire: 60*1
    cors: http://localhost:3000

wiki_dir: wiki